export enum MAIN {
  PROJECT = 'PROJECT',
  BACKGROUND_UPDATER = 'BACKGROUND-UPDATER',
  BLOG = 'BLOG'
}

export enum PROJECT {
  CURRENCY_CONVERTER = 'CURRENCY CONVERTER',
  PASSWORD_GENERATOR = 'PASSWORD GENERATOR',
  TODO = 'TODO',
  MEMORY_GAME = 'MEMORY GAME'
}

export const LOGO = 'https://logo.uplead.com/amazon.com';
